// <auto-generated />
using Autoclean.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Autoclean.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240307103736_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Autoclean.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "2023",
                            Name = "BMW",
                            Price = 2000000m
                        },
                        new
                        {
                            Id = 2,
                            Model = "2024",
                            Name = "Mar",
                            Price = 3000000m
                        },
                        new
                        {
                            Id = 3,
                            Model = "2022",
                            Name = "Toyota",
                            Price = 4000000m
                        },
                        new
                        {
                            Id = 4,
                            Model = "2021",
                            Name = "Mazda",
                            Price = 5000000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
